### ISSUE TITLE
Does not node-turn work on Windows?

### ISSUE THREAD

**Issue by yjgaia** [Atlantis-Software/node-turn#1]
When I `npm run start`, the following logs are output.

```
[2018-05-06T00:51:38.119] [FATAL] DESKTOP-K8LVLHP - { Error: bind EINVAL fe80::c917:20d5:12d3:3771:3478
    at _handle.lookup (dgram.js:266:18)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'bind',
  address: 'fe80::c917:20d5:12d3:3771',
  port: 3478 }
[2018-05-06T00:51:38.125] [FATAL] DESKTOP-K8LVLHP - { Error: bind EINVAL ::1:3478
    at _handle.lookup (dgram.js:266:18)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'bind',
  address: '::1',
  port: 3478 }
[2018-05-06T00:51:38.129] [FATAL] DESKTOP-K8LVLHP - { Error: bind EINVAL 2001:0:9d38:6abd:1810:14be:c4f9:772f:3478
    at _handle.lookup (dgram.js:266:18)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'bind',
  address: '2001:0:9d38:6abd:1810:14be:c4f9:772f',
  port: 3478 }
[2018-05-06T00:51:38.130] [FATAL] DESKTOP-K8LVLHP - { Error: bind EINVAL fe80::1810:14be:c4f9:772f:3478
    at _handle.lookup (dgram.js:266:18)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'bind',
  address: 'fe80::1810:14be:c4f9:772f',
  port: 3478 }
```

Does not node-turn work on Windows?

**Comment by atiertant** [comment]
@Hanul looks like port 3478 is already in use, i never tested on windows (but should work) and ipv6 support is not completely wrote...

**Comment by thelesbianguy** [comment]
same error on Ubuntu

**Comment by dinuchiriac** [comment]
Same issue on Mac,  changing `listeningPort`doesn't help.

**Comment by atiertant** [comment]
@dinuchiriac what about `listeningIps` with ipv4 only address ?

**Comment by dinuchiriac** [comment]
Thanks @atiertant  this helps. It looks like one of the local network connections is not accessible but the default IP address is fine.
