### ISSUE TITLE
Servers are not opening up in default as well as port 80

### ISSUE THREAD

**Issue by amansharmadev** [Atlantis-Software/node-turn#15]
**Port 80**

{ Error: bind EINVAL ::1:80
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'bind',
  address: '::1',
  port: 80 }
{ Error: bind EINVAL fe80::24cf:241b:39c1:4cee:80
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'bind',
  address: 'fe80::24cf:241b:39c1:4cee',
  port: 80 }

// **Default Port**

{ Error: bind EINVAL ::1:3478
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'bind',
  address: '::1',
  port: 3478 }
{ Error: bind EINVAL fe80::24cf:241b:39c1:4cee:3478
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'bind',
  address: 'fe80::24cf:241b:39c1:4cee',
  port: 3478 }

**Comment by jespertheend** [comment]
I'm getting the same issue. It's strange because it was working for me a while back and I haven't changed anything about my setup. It sounds like a permissions issue. Or perhaps the port is already in use.

**Comment by jespertheend** [comment]
Looks like this is only a warning because it was unable to bind to certain ips. It's still binding to the ips I need them to because I get the correct results on https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/.
I did have to whitelist the port on my firewall though.

**Comment by atiertant** [comment]
this error indicate that the port can't be bind, maybe use by an other instance of your project or an other application.
warning you are using ipv6 that is not supported by node-turn
