### ISSUE TITLE
Google Chrome client crashing my turn server? "node-turn": "0.0.1",

### ISSUE THREAD

**Issue by netcrave** [Atlantis-Software/node-turn#3]
```
buffer.js:1185
    throw new TypeError('"value" argument is out of bounds');
    ^

TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1185:11)
    at data.Buffer.writeUIntBE (buffer.js:1216:5)
    at attribute.toBuffer (/home/erratic/cerulean/node_modules/node-turn/lib/attribute.js:354:19)
    at /home/erratic/cerulean/node_modules/node-turn/lib/message.js:223:28
    at Array.forEach (<anonymous>)
    at message.toBuffer (/home/erratic/cerulean/node_modules/node-turn/lib/message.js:215:19)
    at message.resolve (/home/erratic/cerulean/node_modules/node-turn/lib/message.js:239:18)
    at server.<anonymous> (/home/erratic/cerulean/node_modules/node-turn/lib/server.js:124:11)
    at emitTwo (events.js:126:13)
    at server.emit (events.js:214:7)
```

**Comment by netcrave** [comment]
it looks like its happening here: https://github.com/Atlantis-Software/node-turn/blob/master/lib/attribute.js#L352 with that xor'd address.

**Comment by netcrave** [comment]
I can't repro it now, but I'll try to dig a bit deeper and see if I can figure out what is causing it

**Comment by netcrave** [comment]
```
(node:15975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
TURN/DEBUG Receiving UDP: from IPV4://75.172.130.198:59084 to IPV4://206.125.168.69:3478 allocate request TransactionID: 832ec199e75bb30d31e9c80e
  requested-transport: 17
  lifetime: 3600
  fingerprint: 269089819
TURN/FATAL TypeError: "value" argument is out of bounds
(node:15975) UnhandledPromiseRejectionWarning: TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1185:11)
    at data.Buffer.writeUIntBE (buffer.js:1216:5)
    at attribute.toBuffer (/home/erratic/cerulean/node_modules/node-turn/lib/attribute.js:354:19)
    at /home/erratic/cerulean/node_modules/node-turn/lib/message.js:223:28
    at Array.forEach (<anonymous>)
    at message.toBuffer (/home/erratic/cerulean/node_modules/node-turn/lib/message.js:215:19)
    at message.reject (/home/erratic/cerulean/node_modules/node-turn/lib/message.js:266:18)
    at /home/erratic/cerulean/node_modules/node-turn/lib/methods/allocate.js:106:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:15975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
TURN/DEBUG Receiving UDP: from IPV4://75.172.130.198:59088 to IPV4://206.125.168.69:3478 allocate request TransactionID: a0bb21e19707d92d3892f473
  requested-transport: 17
  lifetime: 3600
  fingerprint: 1603794693
TURN/FATAL TypeError: "value" argument is out of bounds
(node:15975) UnhandledPromiseRejectionWarning: TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1185:11)
    at data.Buffer.writeUIntBE (buffer.js:1216:5)
    at attribute.toBuffer (/home/erratic/cerulean/node_modules/node-turn/lib/attribute.js:354:19)
    at /home/erratic/cerulean/node_modules/node-turn/lib/message.js:223:28
    at Array.forEach (<anonymous>)
    at message.toBuffer (/home/erratic/cerulean/node_modules/node-turn/lib/message.js:215:19)
    at message.reject (/home/erratic/cerulean/node_modules/node-turn/lib/message.js:266:18)
    at /home/erratic/cerulean/node_modules/node-turn/lib/methods/allocate.js:106:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:15975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)

```

**Comment by atiertant** [comment]
looks like xoring method crash with some address like in #2
