### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ph4t0o0o0om** [Atlantis-Software/node-turn#6]
Please provide step by step installation guide on WINDOWS. 
Because some command is not working on windows or did not know the equivalent command on windows .

Thank you!

**Comment by ph4t0o0o0om** [comment]
Because I tried this is the output . 

> node start

Using STDOUT for logging
Please create a the log file c:\Windows\Logs\node-turn.log with correct permission
Using sample-config.conf
Please copy with correct permission and modify sample-config.conf to C:\ProgramData\node-turn.conf
[2018-11-08T16:02:53.221] [FATAL] O0DE2018QC0186 - { Error: bind EINVAL fe80::a1c8:102d:e6d4:ea33:3478
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
  code: 'EINVAL',
  errno: 'EINVAL',
  syscall: 'bind',
  address: 'fe80::a1c8:102d:e6d4:ea33',
  port: 3478 }
[2018-11-08T16:02:53.221] [FATAL] O0DE2018QC0186 - { Error: bind EINVAL ::1:3478
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
  code: 'EINVAL',
  errno: 'EINVAL',
  syscall: 'bind',
  address: '::1',
  port: 3478 }

**Comment by atiertant** [comment]
Hi, problem come from IPV6, you could disable IPV6 on all your ifaces or configure an IPV4 to listen in configuration file.

**Comment by ph4t0o0o0om** [comment]
Okay so how can I configure sir? Please help me

**Comment by atiertant** [comment]
use `ipconfig` from `cmd`, choose your IPV4 you want to listen to.
copy sample-config.conf to C:\ProgramData\node-turn.conf
edit this file
uncomment line 12 and replace sample IPV4 by yours and save it.
then `node start`
